PERMISSIONS = [
    ('jobs.create', 'Create jobs', 'jobs'),
    ('jobs.view_assigned', 'View assigned jobs', 'jobs'),
    ('jobs.view_created', 'View jobs created by user', 'jobs'),
    ('jobs.view_all', 'View all job records', 'jobs'),
    ('jobs.edit_assigned', 'Edit assigned jobs', 'jobs'),
    ('jobs.edit_all', 'Edit all jobs', 'jobs'),
    ('jobs.view_photos', 'View vehicle photos', 'jobs'),
    ('jobs.view_amounts', 'View job charges and totals', 'jobs'),
    ('jobs.add_parts', 'Add or change job parts', 'jobs'),
    ('jobs.complete', 'Complete assigned jobs', 'jobs'),
    ('jobs.delete_assigned', 'Delete assigned jobs', 'jobs'),
    ('jobs.delete_all', 'Delete all jobs', 'jobs'),
    ('jobs.assign', 'Assign or reassign jobs', 'jobs'),
    ('jobs.change_status', 'Change job status', 'jobs'),
    ('jobs.print_invoice', 'Print or download invoices', 'jobs'),
    ('expenses.create', 'Submit expenses', 'expenses'),
    ('expenses.view_own', 'View own expenses', 'expenses'),
    ('expenses.view_all', 'View all expenses', 'expenses'),
    ('expenses.edit', 'Edit expenses', 'expenses'),
    ('expenses.delete', 'Delete expenses', 'expenses'),
    ('expenses.approve', 'Approve or reject expenses', 'expenses'),
    ('finance.view_revenue', 'View revenue totals', 'finance'),
    ('finance.view_expenses', 'View expense totals', 'finance'),
    ('finance.view_profit_loss', 'View profit and loss', 'finance'),
    ('finance.export', 'Export financial reports', 'finance'),
    ('users.view', 'View users', 'administration'),
    ('users.approve', 'Approve or reject registrations', 'administration'),
    ('users.manage', 'Create, edit, suspend, or delete users', 'administration'),
    ('roles.manage', 'Manage roles and permissions', 'administration'),
    ('settings.manage', 'Manage workshop settings', 'administration'),
    ('audit.view', 'View audit logs', 'administration'),
]
